BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Christmas_Reduced_entry', 'Christmas Reduced entry - £1.50 3rd £ 4th Dec',1,GETDATE(),GETDATE(),1,1,2,'2011-12-03 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Saturday 3 and Sunday 4 December entry just £1.50 to the zoo. Children can visit Santa in his grotto for £4.50 and receive a lovely gift. We''ll also be doing our popular meerkat feeding with half the money going to the AEECL, working in Madagascar. Come along!	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Late_night_openings', 'Late night openings	',1,GETDATE(),GETDATE(),1,1,2,'2011-08-11 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'The zoo will be opening until 8.30pm on Thursday 11 and Thursday 25 August so come along and take this unique opportunity to see how the animals behave after hours.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Return_within_a_week_for_£1', 'Return within a week for £1	',1,GETDATE(),GETDATE(),1,1,2,'2011-07-25 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'This July and August full-paying visitors can return within a week for £1.  Just ask for a token before you leave the zoo to claim this offer on your next visit.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Father''s_Day_-_kids_go_free', 'Father''s Day - kids go free	',1,GETDATE(),GETDATE(),1,1,2,'2011-06-19 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'This Father''s Day we will be offering one free child entry with each full paying adult so kids can bring their dads to see our dads!	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Love_your_zoo_week', 'Love your zoo week	',1,GETDATE(),GETDATE(),1,1,2,'2011-05-28 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We''re offering one free child entry with a full paying adult this Half-term so why not come along and join us for "Love your Zoo week".Monday 30 - Native Species dayTuesday 31 - Meerkat Day Wednesday 1 June - In-situ DayThursday 2 June - Madagascar DayFriday 3 June - South America Day 	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Race_night-Friday_6_May_7.30pm', 'Race night-Friday 6 May 7.30pm	',1,GETDATE(),GETDATE(),1,1,2,'2011-05-06 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'On Friday 6 May – 7.30pm the Trust is having a “Race night” at the Victoria Hall, Bridge Road, Shaldon - £2 entry (+ optional £1 bet per race). Hopefully you’ll back a winner and raise funds for the Trust. Bring your own picnic and drink. Phone the Trust on 01626 872234 if you would like a ticket	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Mother''s_Day_free_child_entry', 'Mother''s Day free child entry	',1,GETDATE(),GETDATE(),1,1,2,'2011-04-03 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust is delighted that our Madagascan giant jumping rats have a newborn baby making this a family group of five.   Mum and Dad came from Africa Alive in Suffolk and Jersey Zoo.   In 1993 Shaldon Wildlife Trust received its first pair of Madagascan giant jumping rats and at the time became only the second collection in the world to hold and breed these endangered rodents.Visitors can see our new mum this Mother’s Day (Sunday 3 April) when the Trust will be offering one free child entry with every full paying adult.   The Trust is open every day from 10 to 6 (last entry at 5).	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('New_Silvery_marmoset_arrives_at_the_Trust', 'New Silvery marmoset arrives at the Trust	',1,GETDATE(),GETDATE(),1,1,2,'2011-02-12 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Cupid’s arrow was right on target at this romantic time of year when it proved to be love at first sight for Shaldon Wildlife Trust’s new arrival. ‘Gomez a male Silvery marmoset from Paradise Wildlife Park arrived at the Trust last week and staff were delighted when he and our female named Calli hit it off straight away’ said Julie Matthews, Education Officer for the Trust. Shaldon Wildlife Trust actually coordinates this species within Europe, using computer dating to work out the best genetic pairings to keep a healthy breeding programme for this species.  When the breeding programme for this species started in 2002 there were 50 animals in 11 (mostly UK) collections whereas today there are 90  animals in 24 collections throughout the whole of Europe including Hungary, the Netherlands, Germany, Portugal and France with nearly 30 births in just the last year alone.Visitors will be able to see our new Silvery marmoset over Half-term when the Trust will be offering a free child entry with each paying adult.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Golden-headed_lion_tamarin_birth', 'Golden-headed lion tamarin birth	',1,GETDATE(),GETDATE(),1,1,2,'2010-09-10 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust is delighted to have had a baby Golden-headed lion tamarin born. The baby joins the family group that we have here of dad, Wagner who was born in 1995 at Antwerp zoo, mum, Geri who was born in 1994 and came to us from London zoo and their two other offspring. Dad is doing his share of looking after the youngster as is normal for marmosets and tamarins.  In the wild this means that the female has more time to look for food which is particularly important as she has to find food, not only for herself, but also eat enough to provide milk for her young. The female has a gestation period of roughly 130 days and will give birth to one or usually two infants.  The baby is doing extremely well and although for the first couple weeks it was very difficult to spot the infant it can now clearly be seen on its parents back.We are especially pleased with this birth as Golden-headed lion tamarins are an endangered primate and this baby will be an important contribution to the coordinated breeding programme for this species. We take part in the EEP (European Endangered Species Programme) for this species which is the highest level of management for a coordinated breeding programme within Europe. In order to maintain a healthy and genetically diverse population, captive bred tamarins have been reintroduced back into the wild in protected areas in order to try and save this species from extinction.Golden-headed lion tamarins are predominantly black with golden fur on the front of their thick, long mane which resembles a lion. They have long, dextrous fingers with nails on all digits but the big toe, which has a flattened nail which helps them climb like a squirrel through the trees.They feed mainly on fruits but also feed on flowers and nectar, small animal prey such as frogs, snails, lizards and spiders and tree gum.Just 2 to 5 % of the golden-headed lion tamarin''s habitat remains in Brazil due to agricultural, urban and resort development.  	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Late_night_openings', 'Late night openings	',1,GETDATE(),GETDATE(),1,1,2,'2010-08-05 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust will be having late night openings again this August from 6.30 to 8.30 on Thursdays 5, 19 and 26 August.  It is a unique opportunity to see how our animals behave after hours.  Entrance is £6.75 for adults, £5.50 for concessions and £4.50 for children.  Entrance price includes a glass of wine or soft drink.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Official_opening_of_our_new_£150,000_extension', 'Official opening of our new £150,000 extension	',1,GETDATE(),GETDATE(),1,1,2,'2010-06-26 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We are having our Official opening of our new £150,000 extension on Saturday 26 June at 3pm. We are delighted that Kate Reeves, ITV weather presenter, will be opening our extension. Children will have free entry to the Trust from 3pm and adults will be charged the reduced rate of £2.50.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Fermoys_Garden_centre_fun_day', 'Fermoys Garden centre fun day	',1,GETDATE(),GETDATE(),1,1,2,'2010-05-01 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Fermoys Garden Centre at Ipplepen will be having a Family pet show and fun day from 10 to 4 on Saturday 29 May.  There will be bbq, beer tent, children''s entertainment and more.  They are most kindly donating 50% of the profits to the Trust so please go along and help raise some much-needed funds for the Trust.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('New_extension_opens', 'New extension opens	',1,GETDATE(),GETDATE(),1,1,2,'2010-04-02 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Our new extension is now open. This has made the Trust wheelchair accessible for the first time and there are bigger enclosures for some of our animals such as our yellow-breasted capuchins, ring-tailed lemurs and meerkats.  We would love you to come and see our improvements	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Baby_Tamiops_squirrels_now_out_of_nest', 'Baby Tamiops squirrels now out of nest	',1,GETDATE(),GETDATE(),1,1,2,'2010-04-01 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Our four baby Tamiops squirrels are now making their first ventures out of their nestbox.  At 5 weeks old they look like miniature versions of their parents and are extremely cute.  We hope you will be able to come and see this unusual species which is only found at Shaldon and Newquay.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Baby_boom_at_Shaldon_Wildlife_Trust', 'Baby boom at Shaldon Wildlife Trust	',1,GETDATE(),GETDATE(),1,1,2,'2009-09-06 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust is delighted to announce the births of the following animals in the last couple months:Our Yellow breasted capuchin monkey’s, Kizzy and Borba, had their second youngster, their first baby, named Mini B, had just reached his first birthday when his sibling came along.  These animals are critically endangered and are one of the top 25 most endangered primates in the world. Our Brazilian Pied tamarin twins were born in July. Pied tamarins are the rarest primate in the Amazon and notoriously difficult to breed in captivity so we were especially thrilled with this second birth.  A golden-headed lion tamarin baby was born in June, this baby joins a juvenile sibling in the family group. These endangered tamarins have just 2% of their original habitat remaining in Brazil.Twin emperor tamarin’s were born to Mao Mao and Tasha and these are proving to be very mischievous youngsters!And as for the Meerkat’s well ........ triplets followed by quads followed by twins! The Trust has a long history of successes with breeding endangered species and research has shown that Shaldon has the fourth most important collection of critically endangered primates of any zoo in the UK which shows just how unique the Trust is.With all these youngsters we would welcome suggestions for names.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Carnivore_Awareness_Day', 'Carnivore Awareness Day	',1,GETDATE(),GETDATE(),1,1,2,'2009-06-21 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We will be holding a European Carnivore Awareness Day at the Trust on Sunday 21st June.  Dads will get in for half-price as it is Father''s Day and children will get in free if they bring a teddy bear.  As part of the Day we will be having a Teddy Bears picnic from 11 to 2.30 so bring your picnic and your teddy bears.  We will have a Field Hospital where the bears can get a health check.  There will also be face painting and competitions.  	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Baby_yellow-breasted_capuchin_born_at_the_Trust', 'Baby yellow-breasted capuchin born at the Trust',1,GETDATE(),GETDATE(),1,1,2,'2008-07-03 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust is delighted that Kizzy, our yellow-breasted capuchin has given birth on Thursday 3rd July. Kizzy came from Mulhouse zoo, France and her partner Borba came from Zurich zoo, Switzerland. It is Kizzy''s first baby and they are being fantastic parents.We are very pleased as yellow-breasted capuchins are critically endangered and one of the top 25 most endangered primates in the world. They are in only a handful of collections in Europe.Yellow-breasted capuchins are now only found in a very restricted area of the Atlantic Forest of eastern Brazil, one of the richest and most rapidly disappearing ecosystems in the world. Their population is declining drastically not only because of forest destruction, but also because of hunting.Shaldon Wildlife Trust is helping to fund research in the wild which aims to understand the ecology and behaviour of Yellow-breasted capuchins in the wild. Other ongoing projects, to try and prevent their extinction, include working together with the Brazilian Government and farmers to increase the number of protected areas for the species.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Potoroo_baby_born_at_the_Trust', 'Potoroo baby born at the Trust	',1,GETDATE(),GETDATE(),1,1,2,'2008-06-23 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We are delighted to announce that our young Potoroo, born on 19th December, 2007 is now out for all to see and is rapidly getting too big for its mothers pouch.It is a lengthy 170 day process for potoroo''s to develop from their bean sized birth to the stage we are at now. This period is done in the safety of their mothers pouch and it is only now when they become fully developed can we actually see the new addition to our family group.These marsupials are from Australasia and as is often the case with indigenous species they struggle in the wild against introduced animals such as foxes and dogs.Here at Shaldon Wildlife Trust our family group is flourishing, with two females having successfully bred in the past year, things are looking good for this marsupial that stands only 30cm high when fully grown. The parents came from Blackpool zoo and London zoo.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Giant_echiums', 'Giant echiums	',1,GETDATE(),GETDATE(),1,1,2,'2008-06-06 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust may be best known for its collection of rare animals but it also has rare plants and this year there are giants. 10 massive echium plants are in bloom at the Trust this year and are proving to be a magnet for local bees and visitors alike. The tallest two are currently a mighty 17ft 3 inches and 17ft 5 inches and still haven''t quite finished growing yet.The Trust has a wide variety of exotic plants and seeds which anyone can buy from our shop at the entrance to the Trust.They are from the Canary Islands and have taken 4 years to grow but once flowered they then die.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Baby_boom_at_Shaldon_Wildlife_Trust', 'Baby boom at Shaldon Wildlife Trust	',1,GETDATE(),GETDATE(),1,1,2,'2006-11-02 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust is enjoying a baby boom at present. Over the past month we are delighted to have had twin silvery marmosets, twin agoutis (a large South American rodent) and twin African brush-tailed porcupines born.All babies are doing well.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Silvery_marmoset_babies', 'Silvery marmoset babies	',1,GETDATE(),GETDATE(),1,1,2,'2006-09-21 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We are delighted to have had twin silvery marmosets born at the Trust.  Mum is looking after the babies very well although unless they''re suckling the babies are carried by their father or older brothers and sisters.  We actually coordinate the breeding programme for this small South American primate within Europe.  Our group came to us last October from London zoo. Visitors will be able to see the babies at our Open Day on Sunday 8th October where entrance will be just £1 per head.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Silvery_marmosets', 'Silvery marmosets	',1,GETDATE(),GETDATE(),1,1,2,'2005-11-09 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We are delighted to have recently received a family group of Silvery marmosets at the Trust from London Zoo.  London zoo are currently renovating their Clore exhibit which was why these animals needed a new home.  We are especially pleased as we coordinate this species within Europe  	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Jack_the_red_ruffed_lemur_returns_to_Shaldon', 'Jack the red ruffed lemur returns to Shaldon	',1,GETDATE(),GETDATE(),1,1,2,'2005-07-11 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Shaldon Wildlife Trust is delighted that Jack and his son Jackson have come to join their group of bachelor male red-ruffed lemurs.  Jack was actually born at Shaldon and went to Paignton Zoo in 1999 to start their group of red-ruffed lemurs and bred successfully there.  However as their new lemur walk-through exhibit will only have females Paignton asked if we would take Jack back at Shaldon along with his son.  So we now have 3 generations with Thiemo, the father now living with Jude and Jack his sons and Jackson, his grandson. This critically endangered lemur is native to the island of Madagascar and inhabits its eastern evergreen rainforests.  Their preference for large fruiting trees has made them particularly vulnerable from logging practices	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('New_baby_jumping_rat', 'New baby jumping rat	',1,GETDATE(),GETDATE(),1,1,2,'2005-07-01 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We are delighted to have a baby Madagascan giant jumping rat born at the Trust.  In 1993 Shaldon received its first pair of jumping rats and at the time became only the second collection in the world to hold and breed these endangered rodents.  Our male jumping rat came from London zoo in December and our female from Bristol zoo and we are particularly pleased as this is the first offspring from this pair.	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('New_website_goes_live', 'New website goes live	',1,GETDATE(),GETDATE(),1,1,2,'2005-06-18 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'The long awaited new Shaldon Wildlife Trust website went live today (June 18th)! Information on our animals, where to find us, our history and other information can be found here. Please visit the website (or even the Zoo itself!) regularly as updates will happen telling you about new animals and other events. 	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Environment_Day_2005', 'Environment Day 2005	',1,GETDATE(),GETDATE(),1,1,2,'2005-06-05 00:00:00.000',NULL)
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'Sunday 5 June was World Environment Day and to support this day Shaldon Wildlife Trust welcomed 3 staff from the Environment Agency, Exminster. They came to try and get visitors to pledge to make small lifestyle changes that will help make a big difference to our environment. They also worked as ''Keepers for a Day'', helping to feed and clean out our animals. "We thoroughly enjoyed the time we spent at the Trust, learning about and getting involved with the work Shaldon is doing for these endangered species" said Sue Smillie..	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('Wagner,_the_Golden-headed_lion_tamarin_arrives_fro', 'Wagner, the Golden-headed lion tamarin arrives from South Lakes	',1,GETDATE(),GETDATE(),1,1,2,'2005-06-01 00:00:00.000',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'We are delighted to have received a new male Golden-headed lion tamarin from South Lakes Wild Animal Park in Cumbria. Wagner has settled in very well with our female tamarin from London zoo. It was definitely love at first sight and we hope this critically endangered primate will breed successfully at Shaldon. 	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('news_test_two', 'news test description thingie	',1,GETDATE(),GETDATE(),1,1,2,'2011-12-01 15:58:39.153',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'	blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb blerb	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('news_test_two', 'news test description thingie	',1,GETDATE(),GETDATE(),1,1,2,'2011-12-01 15:58:39.153',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'	XX	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('news_test_two', 'news test description thingie	',1,GETDATE(),GETDATE(),1,1,2,'2011-12-01 15:58:39.153',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'	XX	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('news_test_two', 'news test description thingie	',1,GETDATE(),GETDATE(),1,1,2,'2011-12-01 15:58:39.153',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'	XX	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('test2', 'test desc	',1,GETDATE(),GETDATE(),1,1,2,'2011-12-03 18:42:27.043',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'	XX	',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN

BEGIN TRAN insert into content (name,description,created_user,created_date,updated_date,updated_user,auth_group,content_type,start_date, end_date) values ('test2', 'test desc	',1,GETDATE(),GETDATE(),1,1,2,'2011-12-03 19:12:23.950',NULL)	
IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END insert into content_version (content_id,version_id,state_id,data,edit_user,updated_date) values ((select max (id) as id from content),1,1,'		',1,GETDATE()) IF @@ERROR <> 0 BEGIN ROLLBACK TRAN END COMMIT TRAN
